#set page(paper: "us-letter")
#set document(
  title: "Homework 5",
  author: "Uzair Hamed Mohammed",
  date: auto,
)
#set par(justify: true)

#align(center)[
  #title() \
  Uzair Hamed Mohammed \
  CSC 510, Spring 2026 \
  Due 5/4
]

#set enum(numbering: "1.a.i.")

+ Run the dynamic programming algorithm, including reconstruction, to find a longest common subsequence of the DNA sequences/strings

  #align(center)[TGCGCATATG and GTCTCTACAGC]

  Show the table that is generated by the algorithm, and the sequence of steps needed to reconstruct an LCS. Your final answer should be string, and not just its length. This question is not asking for any code.

  #underline[Sol]:

  ```
      0  1  2  3  4  5  6  7  8  9 10 11
      -  G  T  C  T  C  T  A  C  A  G  C
  0   0  0  0  0  0  0  0  0  0  0  0  0
  1 T 0  0  1  1  1  1  1  1  1  1  1  1
  2 G 0  1  1  1  1  1  1  1  1  1  2  2
  3 C 0  1  1  2  2  2  2  2  2  2  2  3
  4 G 0  1  1  2  2  2  2  2  2  2  3  3
  5 C 0  1  1  2  2  3  3  3  3  3  3  4
  6 A 0  1  1  2  2  3  3  4  4  4  4  4
  7 T 0  1  2  2  3  3  4  4  4  4  4  4
  8 A 0  1  2  2  3  3  4  5  5  5  5  5
  9 T 0  1  2  2  3  3  4  5  5  5  5  5
  10G 0  1  2  2  3  3  4  5  5  5  6  6
  ```

  Reconstruction steps from (10,11) (bottom‑right). At each step, if A[i] = B[j] the character is taken and we move to (i‑1, j‑1); otherwise move to the neighbor (i‑1, j) or (i, j‑1) with the larger value, breaking ties arbitrarily (here upward moves chosen when equal).

  - (10,11): A[10]=G, B[11]=C → not equal, left (10,10) has 6 > up (9,11)=5 → move left.
  - (10,10): A[10]=G, B[10]=G → equal, take G, move to (9,9).
  - (9,9): A[9]=T, B[9]=A → not equal, up (8,9)=5 equals left (9,8)=5 → move up to (8,9).
  - (8,9): A[8]=A, B[9]=A → equal, take A, move to (7,8).
  - (7,8): A[7]=T, B[8]=C → not equal, left (7,7)=4 > up (6,8)=4? Actually left = (7,7)=4, up=(6,8)=4 → tie, move up to (6,8).
  - (6,8): A[6]=A, B[8]=C → not equal, left (6,7)=4 > up (5,8)=3 → move left to (6,7).
  - (6,7): A[6]=A, B[7]=A → equal, take A, move to (5,6).
  - (5,6): A[5]=C, B[6]=T → not equal, left (5,5)=3 > up (4,6)=2 → move left to (5,5).
  - (5,5): A[5]=C, B[5]=C → equal, take C, move to (4,4).
  - (4,4): A[4]=G, B[4]=T → not equal, up (3,4)=2 equals left (4,3)=2 → move up to (3,4).
  - (3,4): A[3]=C, B[4]=T → not equal, left (3,3)=2 > up (2,4)=1 → move left to (3,3).
  - (3,3): A[3]=C, B[3]=C → equal, take C, move to (2,2).
  - (2,2): A[2]=G, B[2]=T → not equal, up (1,2)=1 equals left (2,1)=1 → move up to (1,2).
  - (1,2): A[1]=T, B[2]=T → equal, take T, move to (0,1). Stop.

  Collected characters in reverse order: T, C, C, A, A, G → TCCAAG.

  Final longest common subsequence: *TCCAAG*.

+ In class, I’ve made the following claim: given a set of coin denominations, if each denomination is a multiple of the previous one, then the cashier’s algorithm is always optimal. In this problem you will prove this claim for currencies with three denominations. Consider a currency with coins of value 1, a, ab, where a and b are integers bigger than 1. (We saw this in class for the U.S. currency where a = 5 and b = 2).

  + Show that, in any optimal solution, the number of 1-cent coins is at most (a − 1).
  + Show that, in any optimal solution, the number of a-cent coins is at most (b − 1).
  + Use parts (a) and (b) to prove that, for any amount of change $C >= "ab"$, every optimal solution for C has an ab-cent coin. (Hint: as we did in class, prove the contrapositive)

  #underline[Sol]:

  Let an optimal solution use $x$ coins of value $"ab"$, $y$ of value $a$, and $z$ of value $1$.

  + If $z >= a$, replace $a$ ones by one $a$-coin. Coins decrease by $a-1 >= 1$, contradicting optimality. Hence $z <= a-1$.
  + If $y >= b$, replace $b$ coins of value $a$ (total $a b$) by one $"ab"$ coin. Coins decrease by $b-1 >= 1$, contradiction. Hence $y <= b-1$.
  + Prove contrapositive: if an optimal solution has no $"ab"$-cent coin ($x = 0$), then $C < a b$. With $x = 0$, $C = a y + z$, where $y <= b-1$ and $z <= a-1$. Maximum $C$ is $a(b-1) + (a-1) = a b - 1$. Thus $C <= a b - 1 < a b$. Therefore, if $C >= a b$, any optimal solution must contain an $"ab"$-cent coin.

+ For which of the following currencies is the cashier’s algorithm always optimal ? If it’s always optimal, give a brief justification, and if it’s not always optimal, give a counterexample.

  + 1, 13, 72
  + 1, 17, 289
  + 1, 14, 42, 462
  + 1, 6, 11, 34

  #underline[Sol]:

  + $1, 13, 72$: Not always optimal. Counterexample: amount $78$ gives greedy $72 + 1+1+1+1+1+1 = 7$ coins, but $13 + 13 + 13 + 13 + 13 + 13 = 6$ coins is better.
  + $1, 17, 289$: Always optimal. Each denomination is a multiple of the previous ($17$ divides $289$), so the greedy algorithm works by the class claim.
  + $1, 14, 42, 462$: Always optimal. Each coin is a multiple of the previous ($14$ divides $42$, $42$ divides $462$), hence greedy is optimal.
  + $1, 6, 11, 34$: Not always optimal. Counterexample: amount $39$ gives greedy $34 + 1+1+1+1+1 = 6$ coins, but $11+11+11+6 = 4$ coins is better.

+ Construct Huffman codes for the following sets of characters and their frequencies. Draw the Huffman tree (you may attach photos of your trees), write down the codewords for each character, and calculate the total length of the encoded string:

  + (A, 9), (B, 19), (C, 7), (D, 36), (E, 42), (F, 5), (G, 18), (H, 15)
  + (S, 15), (T, 6), (U, 41), (V, 2), (W, 9), (X, 1), (Y, 4), (Z, 38)

  For the sake of having a unique solution, in each iteration of Huffman’s algorithm, make the left child the one with larger frequency.

  #underline[Sol]:

  #image("./attachments/hw5_fig1.png", width: 50%)

  (a) Frequencies: A(9), B(19), C(7), D(36), E(42), F(5), G(18), H(15)

  #table(
    columns: (auto, auto, auto, auto, auto),
    align: center,
    table.header([Char], [Freq], [Codeword], [Len (bits)], [Freq × Len]),
    [A], [9], [$0101$], [4], [36],
    [B], [19], [$011$], [3], [57],
    [C], [7], [$01000$], [5], [35],
    [D], [36], [$10$], [2], [72],
    [E], [42], [$00$], [2], [84],
    [F], [5], [$01001$], [5], [25],
    [G], [18], [$110$], [3], [54],
    [H], [15], [$111$], [3], [45],
  )

  Total length = $36 + 57 + 35 + 72 + 84 + 25 + 54 + 45 = 408$ bits.

  (continued on next page)

  #image("./attachments/hw5_fig2.png", width: 50%)

  (b) Frequencies: S(15), T(6), U(41), V(2), W(9), X(1), Y(4), Z(38)

  #table(
    columns: (auto, auto, auto, auto, auto),
    align: center,
    table.header([Char], [Freq], [Codeword], [Len (bits)], [Freq × Len]),
    [S], [15], [$011$], [3], [45],
    [T], [6], [$01001$], [5], [30],
    [U], [41], [$1$], [1], [41],
    [V], [2], [$0100010$], [7], [14],
    [W], [9], [$0101$], [4], [36],
    [X], [1], [$0100011$], [7], [7],
    [Y], [4], [$010000$], [6], [24],
    [Z], [38], [$00$], [2], [76],
  )

  Total length = $45 + 30 + 41 + 14 + 36 + 7 + 24 + 76 = 273$ bits.
